import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import Footer from "./components/Footer";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <AuthProvider>        
          <body className={`${inter.className} flex flex-col min-h-screen`}>
          <Header />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
          </body>        
      </AuthProvider>
    </html>
  );
}
